version: "3"

services:
  server:
    # image: 
    build: .
    restart: always
    ports:
      - 8000:8000
    command: ["uvicorn", "app.api_server:app", "--host=0.0.0.0"]
    environment:
      DATABASE_URL: postgresql+asyncpg://postgres:postgres@postgres:5437/postgres
    networks:
      - orders_test

  db:
    image: postgres:17
    container_name: orders_test_local_db
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5466:5432"
    networks:
      - orders_test

volumes:
  postgres-data:

networks:
  orders_test:
    driver: bridge