version: "3"

services:
  server:
    # image: 
    build: .
    restart: always
    ports:
      - 8000:8000
    command: ["uvicorn", "app.api_server:app", "--host=0.0.0.0"]
    environment:
      DATABASE_URL: postgresql+asyncpg://postgres:postgres@postgres:5437/postgres
    networks:
      - <NETWORK_NAME>

  postgres:
    image: postgres:15
    restart: always
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5466:5432"
    networks:
      - <NETWORK_NAME>

volumes:
  postgres-data:

networks:
  <NETWORK_NAME>:
    driver: bridge